[package]
authors = ["James Munns <james.munns@gmail.com>"]
categories = ["embedded", "hardware-support", "no-std"]
description = "HAL for the nRF52 family of microcontrollers"
keywords = ["arm", "cortex-m", "nrf52", "hal"]
license = "MIT OR Apache-2.0"
name = "nrf52-hal"
repository = "https://github.com/jamesmunns/nrf52-hal"
version = "0.0.1"

[dependencies]
cortex-m = "0.4.3"
nb = "0.1.1"

[dependencies.nrf52]
features = ["rt"]
version = "0.2.0"

[dependencies.cast]
default-features = false
version = "0.2.2"

[dependencies.embedded-hal]
features = ["unproven"]
version = "0.1.2"

[features]
doc = []
rt = ["nrf52/rt"]
unproven = ["embedded-hal/unproven"]
default = ["rt"]

[profile.dev]
incremental = false
codegen-units = 1

[profile.release]
debug = true
lto = true
